version: '3.8'

services:
  db:
    image: postgres
    container_name: applicationpayment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment
    ports:
      - "5433:5432"

volumes:
  db_data: